name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci --force
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps --force
    - name: Run Playwright tests - Smoke
      run: npx playwright test --project=regression --grep @smoke
    - name: Generate Allure report
      run: |
        npx --yes allure-commandline@2.21.0 generate allure-results --clean -o allure-report || allure generate allure-results --clean -o allure-report
    - name: Upload test reports and artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: test-reports
        path: |
          allure-report
          allure-results
        retention-days: 30
        if-no-files-found: warn
    - name: Configure GitHub Pages
      uses: actions/configure-pages@v4

    - name: Upload Allure report to GitHub Pages artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./allure-report

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4